spring:
  data:
    mongodb:
      authentication-database: mzitu
      database: mzitu
      host: 59.110.159.173
      port: 27101
      username: mzitu
      password: mzitu191211!!!
      
spider:
  init: false
  increment: false
